# Generated by Django 5.1.2 on 2024-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appka', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='russia', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='myhotel', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='moscow', max_length=50),
        ),
    ]
